### PR TITLE
👨‍🏭 Special character fix

### PR DESCRIPTION
**Pull request by 7loud**
Issue https://github.com/AngryKiller/iTunes-bridge/issues/9

### CODE REVIEW

**Comment by AngryKiller** [comment]
Isn't it possible to let the decode part to iTunes-bridge itself instead of leaving it to the user? I will investigate this in the next days when I'll have time, but otherwise thank you for the contribution!

**Comment by AngryKiller** [comment]
I moved the decodeURI part to the part where iTunes-bridge gets the result from the shell so it avoids decoding each value in the user code etc. Tested it on a Windows 7 VM but cmd always shows ?????? when you input special characters to it, and I didn't have time to test it with an app using the package. Tell me if it works for you, and if it does I'll merge the fix!

**Comment by 7loud** [comment]
image
image

**Comment by AngryKiller** [comment]
Thanks

**Pull request merged**
